force-app/main/default/objects/Purchase__c/Purchase__c.object-meta.xml
<CustomObject>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase__c/fields/Actual_Rate_buyed__c.field-meta.xml
<CustomField>
    <fullName>Actual_Rate_buyed__c</fullName>
    <label>Actual Rate buyed</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase__c/fields/Product_image__c.field-meta.xml
<CustomField>
    <fullName>Product_image__c</fullName>
    <formula>IMAGE(  Drive_url__c ,&apos;Image&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product_image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase__c/fields/Sell_Rate__c.field-meta.xml
<CustomField>
    <fullName>Sell_Rate__c</fullName>
    <description>divya automobiles want to sell rate</description>
    <label>Sell Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase__c/fields/Total_Amount_Bought__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Bought__c</fullName>
    <formula>Quantity__c  *  Sell_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount Bought</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PurchaseDetails.cls
public class PurchaseDetails {

    @AuraEnabled(Cacheable=true)
    public static List<Purchase__c> returnDetails(String searchPurchase) {
        String searchTerm = '%' + String.escapeSingleQuotes(searchPurchase) + '%';

        List<Purchase__c> allpurchasedetails = [SELECT Id, Actual_Rate_buyed__c, Invoice_Number__c, Name, Product_image__c, Quantity__c, Sell_Rate__c, Total_Amount_Bought__c 
                                                FROM Purchase__c 
                                                WHERE Name LIKE :searchTerm LIMIT 5];

        return allpurchasedetails;
    }

    @AuraEnabled(Cacheable=true)
    public static List<Purchase__c> getDetails(String recordId) {
        List<Purchase__c> allpurchasedetails = [SELECT Id, Actual_Rate_buyed__c, Invoice_Number__c, Name, Product_image__c, Quantity__c, Sell_Rate__c, Total_Amount_Bought__c 
                                                FROM Purchase__c 
                                                WHERE Id = :recordId LIMIT 1];

        return allpurchasedetails;
    }  
}