force-app/main/default/objects/Purchase__c/Purchase__c.object-meta.xml
<CustomObject>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase__c/fields/Drive_url__c.field-meta.xml
<CustomField>
    <fullName>Drive_url__c</fullName>
    <label>Drive url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PurchaseController.cls
public class PurchaseController {
    public static void afterUpdate(list<purchase__C> newValues){
        string DriveUrl ;
        List<purchase__C> updatedValues = new List<purchase__C>();
        for(purchase__C pur : newValues){
          DriveUrl = pur.Drive_url__c;
        }
        if(DriveUrl != ''){
            system.debug(' DriveUrl   '+DriveUrl);
            DeleteContent.deleteContents();
        }
    }
}